"""initial_schema

Revision ID: 52cb6af41ff2
Revises: 
Create Date: 2026-05-10 18:31:49.581943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cb6af41ff2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('onboarding_status', sa.Enum('pending', 'in_progress', 'complete', 'restricted', name='onboardingstatus'), nullable=False),
    sa.Column('charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('details_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_table('vendors')
    sa.Enum(name='onboardingstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
